version: '2'
services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_ROOT_DATABASE: simplechat
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      
  ezops-teste:
    depends_on:
      - mongo
    container_name: ezOps-teste
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - ezOps-teste-network
    volumes:
      - ezOps-teste_volume:/data
volumes:
  ezOps-teste_volume:
networks:
  ezOps-teste-network:
