version: '2'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      
  ezops-teste:
    depends_on:
      - mongo
    container_name: ezOps-teste
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - ezOps-teste-network
    volumes:
      - ezOps-teste_volume:/data
volumes:
  ezOps-teste_volume:
networks:
  ezOps-teste-network:

  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80