version: '2'
services:
  mongo:
    container_name: mongodb-ezops
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      
  ezops-teste:
    depends_on:
      - mongo
    container_name: ezOps-backend
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  nginx:
    container_name: nginx-ezops
    image: nginx:latest
    restart: always
    ports:
      - 80:80