version: '2'
services:

      
  ezops-teste:
    depends_on:
      - nginx
    container_name: ezOps-teste
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - ezOps-teste-network
    volumes:
      - ezOps-teste_volume:/data
volumes:
  ezOps-teste_volume:
networks:
  ezOps-teste-network:

  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80