version: '2'

networks:
    network-ezops:
       driver:
          bridge

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    networks:
      - network-ezops 
    env_file:
      - .env
      
  backend:
    depends_on:
      - mongodb
    container_name: backend
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - network-ezops 
    env_file:
      - .env

  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - 80:80
    networks:
      - network-ezops   
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf"
      - "./hosts:/etc/hosts"

